rocRAND: Simple Distributions Example (C++)
amd/rocm-examples pull request #1
Opened 2022-07-11 13:50 UTC by mfep

2022-08-15 19:35 UTC, saadrahim approved these changes

2022-08-15 22:05 UTC, saadrahim requested changes
Please rename the example_library_template to use camel case. This is to match folder names of the libraries.

2022-08-22 14:52 UTC, mfep commented
> Please rename the example_library_template to use camel case. This is to match folder names of the libraries.

Done as requested.

2022-08-23 13:58 UTC, saadrahim approved these changes

2022-08-23 13:58 UTC, saadrahim commented
Please merge squash.

2022-08-23 14:47 UTC, merged