Add linting action for documentation
amd/rocm-examples pull request #119
Opened 2024-05-15 15:40 UTC by dgaliffiAMD

Addresses Issue: [53](https://github.com/ROCm/rocm-examples/issues/53)

2024-05-15 15:41 UTC, dgaliffiAMD commented
Starting the process, but need to fix the existing errors first.

2024-05-16 16:21 UTC, dgaliffiAMD commented
Fixed the `markdownlint` errors in the project.

2024-05-22 08:51 UTC, Naraenda requested changes
The markdown improvements look good. I had a problem with some of the code-blocks turning into math-blocks and a few minor nits, but other than that LGTM.

2024-05-22 08:51 UTC, Naraenda commented on Applications/prefix_sum/README.md
> +![prefix_sum_diagram.svg](prefix_sum_diagram.svg)
The text in between the `[...]` should be a description. There are more of such cases (just search for `![`).

2024-05-22 08:51 UTC, Naraenda commented on Dockerfiles/README.md
> +``` bash
```suggestion
```shell
```

Consistency with other code blocks.

2024-05-22 08:51 UTC, Naraenda commented on HIP-Basic/matrix_multiplication/README.md
> +## Command line interface
```suggestion
### Command line interface
```

Header level got changed?

2024-05-22 08:51 UTC, Naraenda commented on HIP-Basic/runtime_compilation/README.md
>  ![hiprtc.svg](hiprtc.svg)
Unrelated to the change, but the `[...]`-part should contain the image description.

2024-05-22 08:51 UTC, Naraenda commented on LLVM_ASAN/Using-Address-Sanitizer-with-a-Short-HIP-Application.md
> +```gdb
I don't think `gdb` is a valid code-block language. It might be better to just use `text` in these cases.

2024-05-22 08:51 UTC, Naraenda commented on LLVM_ASAN/Using-Address-Sanitizer-with-a-Short-HIP-Application.md
> +```gdb
I don't think gdb is a valid code-block language. It might be better to just use text in these cases.

2024-05-22 08:51 UTC, Naraenda commented on Libraries/rocSPARSE/level_2/bsrmv/README.md
> +```math
This should not be denoted with `math` as most Markdown renderers will parse this a $\LaTeX$ or KaTeX block.

```suggestion
```cpp
```

There are more of these cases, but I'm only pointing out this one to not clog up the rest of the review.

2024-05-22 16:51 UTC, dgaliffiAMD reviewed
Thanks for the feedback. I have made your suggested changes.

2024-05-22 16:51 UTC, dgaliffiAMD commented on LLVM_ASAN/Using-Address-Sanitizer-with-a-Short-HIP-Application.md
> +```gdb
Updated. Changed to `text`.

2024-05-22 16:51 UTC, dgaliffiAMD commented on LLVM_ASAN/Using-Address-Sanitizer-with-a-Short-HIP-Application.md
> +```gdb
Updated. Changed to `text`.

2024-05-22 17:42 UTC, dgaliffiAMD commented on HIP-Basic/matrix_multiplication/README.md
> +## Command line interface
My mistake. Changing it back to H3.

2024-05-23 08:58 UTC, Naraenda approved these changes
LGTM! Thanks!

2024-05-23 14:07 UTC, merged