VS2017 and VS2022 supported. Bugs fixed.
amd/rocm-examples pull request #22
Opened 2023-01-19 15:02 UTC by Beanavil

Some bugs solved.
VS2017 and VS2022 project files added.

2023-01-24 10:16 UTC, hchevanne commented
- In vulkan_interop_vs2017.sln, vulkan_interop_vs2019.sln and vulkan_interop_vs2022.sln:

Missing "$(GLFW_DIR)\include" in "\<AdditionalIncludeDirectories\>" property for both **HIP_clang** and **HIP_nvcc** toolsets (**Debug** and **Release**)
Missing "<AdditionalLibraryDirectories>$(GLFW_DIR)\lib-**vc2019**</AdditionalLibraryDirectories>" property for both HIP_clang and HIP_nvcc toolsets (Debug and Release)
Note: _**vc2019** should changed according to the target version of VS, (2017, 2019 or 2022)._


- In opengl_interop_vs2017.sln, opengl_interop_vs2019.sln and opengl_interop_vs2022.sln:

Missing "$(GLFW_DIR)\include" in "\<AdditionalIncludeDirectories\>" property for both **HIP_clang** and **HIP_nvcc** toolsets (**Debug** and **Release**)
Missing "<AdditionalLibraryDirectories>$(GLFW_DIR)\lib-**vc2019**</AdditionalLibraryDirectories>" property for both HIP_clang and HIP_nvcc toolsets (Debug and Release)
Note: _**vc2019** should changed according to the target version of VS, (2017, 2019 or 2022)._

2023-01-24 16:35 UTC, Snektron commented
@hchevanne The reason that those include/library paths were removed is because these examples are set up to benefit from [vcpkg integrate](https://learn.microsoft.com/en-us/vcpkg/commands/integrate) (as described in the readme). We can add GLFW_DIR usage as a fallback strategy, though.

2023-01-25 15:05 UTC, hchevanne commented
This was reported by the CI team.
Also, there are some typos in **Libraries/rocRAND/simple_distributions_cpp** vcxproj files for vs2017, vs2019 and vs2022 which also break the CI:
**-Wno-#warnings** instead of **-Wno-warnings**

2023-01-26 08:42 UTC, Snektron commented
> Also, there are some typos in Libraries/rocRAND/simple_distributions_cpp vcxproj files for vs2017, vs2019 and vs2022.
-Wno-#warnings instead of -Wno-warnings

[clang documentation](https://clang.llvm.org/docs/DiagnosticsReference.html#w-warnings) lists this flag as being `-Wno-#warnings` (`-W#warnings`) and not as `-Wno-warnings`. Indeed, when I swap out the current `-Wno-#warnings` with `-Wno-warnings` I get warnings, so Im not really sure what should be changed here...

2023-01-31 17:31 UTC, emankov commented
@Beanavil, @Snektron, hello!

May I ask you to make your PRs `a bit smaller`? Actually, much smaller, at least 10x times smaller. It will save us time, and it is how the open-source world lives. There is no need in putting everything in one basket.

Thanks in advance,
Evgeny (HIP/HIPIFY/HIP-VS dev team)

2023-01-31 17:36 UTC, emankov commented
> > Also, there are some typos in Libraries/rocRAND/simple_distributions_cpp vcxproj files for vs2017, vs2019 and vs2022.
> > -Wno-#warnings instead of -Wno-warnings
> 
> [clang documentation](https://clang.llvm.org/docs/DiagnosticsReference.html#w-warnings) lists this flag as being `-Wno-#warnings` (`-W#warnings`) and not as `-Wno-warnings`. Indeed, when I swap out the current `-Wno-#warnings` with `-Wno-warnings` I get warnings, so Im not really sure what should be changed here...

Maybe, these options for the `HIP_nvcc` Platform Toolset should be changed? You are trying to feed `nvcc` with clang's options - that's the point.

2023-02-02 10:13 UTC, emankov requested changes
Please, fix the rest of `vcxproj` and `sln` files based on the existing comments.

P.S.
There are other changes awaiting merge, so, let's merge these this week.

Thanks,
Evgeny

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/assembly_to_executable/assembly_to_executable_vs2019.sln
>  Microsoft Visual Studio Solution File, Format Version 12.00
A solution file's header should start from `Microsoft Visual Studio Solution File, Format Version XX.YY`, empty lines are unacceptable.

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/assembly_to_executable/assembly_to_executable_vs2019.vcxproj
> +    <VCProjectVersion>$(MSBuildVersion)</VCProjectVersion>
Should be an exact value, `16.0` in this particular case. Substitution even if it takes place is incorrect for `vcxproj` file targeting a specific version of VS - 2019.

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/assembly_to_executable/assembly_to_executable_vs2022.sln
> +EndProject
Why solutions for every single project are provided as well? What's the point?

2023-02-02 10:13 UTC, emankov commented on Applications/floyd_warshall/floyd_warshall_vs2017.vcxproj
> +  </PropertyGroup>
Better to have this `PropertyGroup` above just after `ProjectConfigurations` `ItemGroup`. It is not an error, the reason is to have a unified and standard AMAP representation of all the projects for ease of support, first of all.

2023-02-02 10:13 UTC, emankov commented on Applications/floyd_warshall/floyd_warshall_vs2019.vcxproj
> +    <VCProjectVersion>$(MSBuildVersion)</VCProjectVersion>
Should be 16.0

2023-02-02 10:13 UTC, emankov commented on Applications/floyd_warshall/floyd_warshall_vs2022.vcxproj
> +  </PropertyGroup>
`VCProjectVersion` should be 17.0, and the `PropertyGroup` `Globals` should be moved up (see the above comment on where).

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/assembly_to_executable/assembly_to_executable_vs2017.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/assembly_to_executable/assembly_to_executable_vs2022.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/bandwidth/bandwidth_vs2019.vcxproj
> +    <VCProjectVersion>$(MSBuildVersion)</VCProjectVersion>
16.0

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/bit_extract/bit_extract_vs2017.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/bit_extract/bit_extract_vs2019.sln
>  Microsoft Visual Studio Solution File, Format Version 12.00
Sln's header should start with `Microsoft Visual Studio Solution File, Format Version XX.YY`

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/bit_extract/bit_extract_vs2019.vcxproj
> +    <VCProjectVersion>$(MSBuildVersion)</VCProjectVersion>
16.0

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/bit_extract/bit_extract_vs2022.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/cooperative_groups/cooperative_groups_vs2017.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/cooperative_groups/cooperative_groups_vs2019.sln
>  Microsoft Visual Studio Solution File, Format Version 12.00
Sln's header should start with `Microsoft Visual Studio Solution File, Format Version XX.YY`

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/cooperative_groups/cooperative_groups_vs2019.vcxproj
> +    <VCProjectVersion>$(MSBuildVersion)</VCProjectVersion>
16

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/cooperative_groups/cooperative_groups_vs2022.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/device_globals/device_globals_vs2017.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/device_globals/device_globals_vs2019.sln
>  Microsoft Visual Studio Solution File, Format Version 12.00
Sln's header should start with `Microsoft Visual Studio Solution File, Format Version XX.YY`

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/device_globals/device_globals_vs2019.vcxproj
> +    <VCProjectVersion>$(MSBuildVersion)</VCProjectVersion>
16.0

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/device_globals/device_globals_vs2022.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/device_query/device_query_vs2017.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/device_query/device_query_vs2019.sln
>  Microsoft Visual Studio Solution File, Format Version 12.00
Sln's header should start with `Microsoft Visual Studio Solution File, Format Version XX.YY`

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/device_query/device_query_vs2019.vcxproj
> +    <VCProjectVersion>$(MSBuildVersion)</VCProjectVersion>
16.0

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/device_query/device_query_vs2022.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/dynamic_shared/dynamic_shared_vs2017.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/dynamic_shared/dynamic_shared_vs2019.sln
>  Microsoft Visual Studio Solution File, Format Version 12.00
Sln's header should start with `Microsoft Visual Studio Solution File, Format Version XX.YY`

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/dynamic_shared/dynamic_shared_vs2019.vcxproj
> +    <VCProjectVersion>$(MSBuildVersion)</VCProjectVersion>
16.0

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/dynamic_shared/dynamic_shared_vs2022.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/events/events_vs2017.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/events/events_vs2019.vcxproj
> +    <VCProjectVersion>$(MSBuildVersion)</VCProjectVersion>
16.0

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/events/events_vs2019.sln
>  Microsoft Visual Studio Solution File, Format Version 12.00
Sln's header should start with `Microsoft Visual Studio Solution File, Format Version XX.YY`

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/events/events_vs2022.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/gpu_arch/gpu_arch_vs2017.vcxproj
> +  </PropertyGroup>
Same as above

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/gpu_arch/gpu_arch_vs2019.sln
>  Microsoft Visual Studio Solution File, Format Version 12.00
Sln's header should start with `Microsoft Visual Studio Solution File, Format Version XX.YY`

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/gpu_arch/gpu_arch_vs2019.vcxproj
> +    <VCProjectVersion>$(MSBuildVersion)</VCProjectVersion>
16.0

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/gpu_arch/gpu_arch_vs2022.vcxproj
> +    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
Same as above. 17.0.

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/hello_world/hello_world_vs2017.vcxproj
> +  </PropertyGroup>
Same as above. 15.0.

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/hello_world/hello_world_vs2019.vcxproj
> +  </PropertyGroup>
Same as above. 16.0.

2023-02-02 10:13 UTC, emankov commented on HIP-Basic/hello_world/hello_world_vs2022.vcxproj
> +  </PropertyGroup>
Same as above. 17.0.

2023-02-02 15:52 UTC, Beanavil commented
@emankov I'm checking the nvcc documentation, and seems like the proper way of passing this compiler options is with [--compiler-options or -Xcompiler](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#compiler-options-options-xcompiler), so `-Xcompiler "-w"` should work. Could you check if this is the case?

2023-02-02 16:33 UTC, Beanavil commented on HIP-Basic/assembly_to_executable/assembly_to_executable_vs2022.sln
> +EndProject
AFAIK we were asked to include those solution projects, but I was not in the project when this happened. Also, this allows to have each example as a self-contained one, this has advantages such as being able to build a single example in VScode without needing to build the whole examples project.

2023-02-02 16:37 UTC, saadrahim commented on HIP-Basic/assembly_to_executable/assembly_to_executable_vs2022.sln
> +EndProject
It is a requirement to have a solution for each example. Each example can must be buildable separately and as part of the entire project as well. This is for end user convinience.

2023-02-02 16:41 UTC, emankov commented on HIP-Basic/assembly_to_executable/assembly_to_executable_vs2022.sln
> +EndProject
Ok, got it, thanks!

2023-02-02 16:55 UTC, emankov commented
> @emankov I'm checking the nvcc documentation, and seems like the proper way of passing this compiler options is with [--compiler-options or -Xcompiler](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#compiler-options-options-xcompiler), so `-Xcompiler "-w"` should work. Could you check if this is the case?

Well, we are talking about different compilers, right? Different compilers - different options. There is no any guaranteed correspondence between them. There are some, which came from the GNU C/C++ world, and that is it.

As for the `-Xcompiler`, it is for passing options to nvcc's compiler's frontend/preprocessor directly, and that is it. I do not observe an exact correspondence between warning-related options in `clang` and in `nvcc`.

Analogues redirecting options exist for clang driver: `-Xpreprocessor`, `-Xclang`, `-Xassembler`, etc...

2023-02-03 13:51 UTC, Beanavil commented
You are right, `-Xcompiler` should not be used in this case. However, `-w` (or, equivalently, `--disable-warnings`) alone seems like [does the same](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#generic-tool-options) as `--Wno-#warnings` for clang.

2023-02-07 15:46 UTC, saadrahim commented
@Beanavil and @Snektron what is left to address @emankov's concerns? Can we merge this soon?

2023-02-07 16:28 UTC, saadrahim approved these changes
Please ensure this is the last PR that is this large. Bug fixes should be a separate PR while feature implementations should come in logical chunks. 477 files are impossible to review.

2023-02-07 21:41 UTC, Beanavil commented
@saadrahim the changes proposed by @emankov are ready to be pushed, I just wanted some reply to my last comment, so I can be sure that the mentioned nvcc option works properly on your end (I can't check it myself).

2023-02-08 13:28 UTC, emankov approved these changes
Thanks!

2023-02-08 13:43 UTC, merged