HIP SDK Application Examples (part I)
amd/rocm-examples pull request #50
Opened 2023-10-31 08:21 UTC by Beanavil

This PR covers the HIP SDK Application examples implemented during the past months. In particular, we add the following examples to the existing suite:
- Monte Carlo Pi estimation
- Prefix sum
- Floyd-Warshall
- Histogram
- Convolution
- Bitonic sort

2023-11-02 16:26 UTC, saadrahim requested changes
Please add linting to this project based on https://github.com/RadeonOpenCompute/ROCm/blob/develop/.github/workflows/linting.yml

After adding linting, ensure that linting passes.

2023-11-03 13:26 UTC, saadrahim approved these changes

2023-11-07 19:51 UTC, saadrahim commented
@Beanavil  can you please resolve conflicts so this can be merged?

2023-11-07 23:53 UTC, Beanavil commented
@saadrahim the conflicts should be solved now.

2023-11-10 14:52 UTC, merged