HIP "Cookbook" Example Suite (part 1)
amd/rocm-examples pull request #6
Opened 2022-09-12 13:44 UTC by mfep

- device_query: Program that showcases how properties from the device may be queried.
- dynamic_shared: Program that showcases how to use dynamic shared memory with the help of a simple matrix transpose kernel.
- hello_world: Simple program that showcases launching kernels and printing from the device.
- hipify: Simple program and build definitions that showcase automatically converting a CUDA `.cu` source into portable HIP `.hip` source.
- matrix_multiplication: Multiply two dynamically sized matrices utilizing shared memory.
- occupancy: Shows how to find optimal configuation parameters for a kernel launch with maximum occupancy.
- saxpy: Implements the $Y_i=aX_i+Y_i$ kernel and explains basic HIP functionality.

2022-09-12 15:38 UTC, saadrahim commented
I don't like the use of the term cookbook. Perhaps hipruntime instead.

2022-09-12 16:02 UTC, saadrahim commented on Cookbook/hipify/main.cu
> +#define CHECK(cmd)                                                                          \
should the checks be in common?

2022-09-12 16:03 UTC, saadrahim commented on Cookbook/hipify/main.cu
> +#define CHECK(cmd)                                                                          \
Sorry, this is a CUDA file, makes sense as is.

2022-09-16 16:54 UTC, saadrahim requested changes
Please change the cookbook folder to HIP_Basic or something similar.

2022-09-20 07:21 UTC, mfep commented
> Please change the cookbook folder to HIP_Basic or something similar.

Done as requested.

2022-09-22 17:27 UTC, saadrahim approved these changes

2022-09-22 17:28 UTC, merged